// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtqAYUnCTwUF7UGsW5DbMeTRvaqSK4QCE',
    appId: '1:906609544893:web:70a87b2099540ef63371d4',
    messagingSenderId: '906609544893',
    projectId: 'datavault-cf711',
    authDomain: 'datavault-cf711.firebaseapp.com',
    storageBucket: 'datavault-cf711.firebasestorage.app',
    measurementId: 'G-YBQDVJM4S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBzHyyjtGdoGVs4r0bRm37iBMU1quIv8',
    appId: '1:906609544893:android:647726b76e206fed3371d4',
    messagingSenderId: '906609544893',
    projectId: 'datavault-cf711',
    storageBucket: 'datavault-cf711.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPV8Ixjn8WtqoDjKVm_ri6dPkvyyC9OXU',
    appId: '1:906609544893:ios:e7f599e7563ea71e3371d4',
    messagingSenderId: '906609544893',
    projectId: 'datavault-cf711',
    storageBucket: 'datavault-cf711.firebasestorage.app',
    iosBundleId: 'com.balaji.datavault',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPV8Ixjn8WtqoDjKVm_ri6dPkvyyC9OXU',
    appId: '1:906609544893:ios:dd9ace107c6335213371d4',
    messagingSenderId: '906609544893',
    projectId: 'datavault-cf711',
    storageBucket: 'datavault-cf711.firebasestorage.app',
    iosBundleId: 'com.example.workflo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtqAYUnCTwUF7UGsW5DbMeTRvaqSK4QCE',
    appId: '1:906609544893:web:51a4a07286b910c03371d4',
    messagingSenderId: '906609544893',
    projectId: 'datavault-cf711',
    authDomain: 'datavault-cf711.firebaseapp.com',
    storageBucket: 'datavault-cf711.firebasestorage.app',
    measurementId: 'G-GZCHNLZ20D',
  );
}
