// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7SnBmxCLoQSVuqjAQ24eJAUQdG0vZ4Os',
    appId: '1:13185636801:web:96ec14e7ca90caf0873740',
    messagingSenderId: '13185636801',
    projectId: 'workflow-5ef11',
    authDomain: 'workflow-5ef11.firebaseapp.com',
    storageBucket: 'workflow-5ef11.firebasestorage.app',
    measurementId: 'G-4DPG0QQHJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChiXrwhG8BNozWZIrvlvrseElHesRwTq8',
    appId: '1:13185636801:android:218b754b7b50b0d7873740',
    messagingSenderId: '13185636801',
    projectId: 'workflow-5ef11',
    storageBucket: 'workflow-5ef11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjA0jOJPlujak8VxtQan0VikO9b5tKQ0Y',
    appId: '1:13185636801:ios:2f45b76356f3e0da873740',
    messagingSenderId: '13185636801',
    projectId: 'workflow-5ef11',
    storageBucket: 'workflow-5ef11.firebasestorage.app',
    iosBundleId: 'com.example.workflo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjA0jOJPlujak8VxtQan0VikO9b5tKQ0Y',
    appId: '1:13185636801:ios:2f45b76356f3e0da873740',
    messagingSenderId: '13185636801',
    projectId: 'workflow-5ef11',
    storageBucket: 'workflow-5ef11.firebasestorage.app',
    iosBundleId: 'com.example.workflo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7SnBmxCLoQSVuqjAQ24eJAUQdG0vZ4Os',
    appId: '1:13185636801:web:dbc63b9ac202ba82873740',
    messagingSenderId: '13185636801',
    projectId: 'workflow-5ef11',
    authDomain: 'workflow-5ef11.firebaseapp.com',
    storageBucket: 'workflow-5ef11.firebasestorage.app',
    measurementId: 'G-VJZS06KE4D',
  );
}
